remote_server_login_details:
  - remote_user: XXXXX
    remote_password:  'XXXXX'

input_parameters:
  - key: username
    help_text: 'Enter SFTP user name without spaces'
    display_name: 'Client SFTP user name'
  - key: clientType
    help_text: 'Select one of the followings, onsite or cloud'
    display_name: 'Client Type'
  - key: accountType
    help_text: 'Select one of the followings, temporary or permenant'
    display_name: 'SFTP Account Type'
  - key: validityPeriod
    help_text: 'Please specify account validity period if the account type is temporary'
    display_name: 'Account validity Period'
  - key: serverIP
    help_text: 'IP of the server which SFTP account needs to be created'
    display_name: 'Server IP or Domain Name'
  - key: requesterEmailAddress
    help_text: 'Email address of the person who request the SFTP account [this person will receive the account details]'
    display_name: 'Requester Email Address'

email_configurations:
  user_name: 'nipuna499@gmail.com'
  password: 'PhR6T516$'
  host: 'smtp.gmail.com'
  port: '587'

ldap_directory_details:
  ldap_host: 'dev-ldap.orangehrm.com'
  ldap_port: '636'
  ldap_bind_user_name: 'cn=admin,dc=orangehrm,dc=com'
  ldap_bind_user_password: 'pL32Fk7UxU2o'

sftp_account_deletion_notification:
  time_period: [6,3]